// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type {
    ComputeRoutesData,
    ComputeRoutesErrors,
    ComputeRoutesResponses,
    GetCategoriesData,
    GetCategoriesErrors,
    GetCategoriesResponses,
    GetPlaceByIdData,
    GetPlaceByIdErrors,
    GetPlaceByIdResponses,
    GetPlacesData,
    GetPlacesErrors,
    GetPlacesResponses
} from './types.gen'

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean
> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>
}

/**
 * Get Categories
 */
export const getCategories = <ThrowOnError extends boolean = false>(
    options?: Options<GetCategoriesData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetCategoriesResponses, GetCategoriesErrors, ThrowOnError>({
        url: '/categories',
        ...options
    })

/**
 * Get Places
 */
export const getPlaces = <ThrowOnError extends boolean = false>(
    options?: Options<GetPlacesData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetPlacesResponses, GetPlacesErrors, ThrowOnError>({
        url: '/places',
        ...options
    })

/**
 * Get Place By Id
 */
export const getPlaceById = <ThrowOnError extends boolean = false>(
    options: Options<GetPlaceByIdData, ThrowOnError>
) =>
    (options.client ?? client).get<GetPlaceByIdResponses, GetPlaceByIdErrors, ThrowOnError>({
        url: '/places/{id}',
        ...options
    })

/**
 * Compute Routes
 */
export const computeRoutes = <ThrowOnError extends boolean = false>(
    options: Options<ComputeRoutesData, ThrowOnError>
) =>
    (options.client ?? client).post<ComputeRoutesResponses, ComputeRoutesErrors, ThrowOnError>({
        url: '/routes/compute',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })
