// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {})
}

/**
 * CategoriesPublic
 */
export type CategoriesPublic = {
    /**
     * Categories
     */
    categories: Array<CategoryPublic>
}

/**
 * Category
 */
export type Category =
    | 'entertainment'
    | 'heritage'
    | 'landmarks'
    | 'museums'
    | 'nature'
    | 'shopping'

/**
 * CategoryPublic
 */
export type CategoryPublic = {
    category: Category
    /**
     * Count
     */
    count: number
}

/**
 * Description
 */
export type Description = {
    /**
     * Content
     */
    content: string
    /**
     * Source
     */
    source: string
}

/**
 * DriveRoute
 */
export type DriveRoute = {
    origin: PlaceId
    destination: PlaceId
    /**
     * Mode
     */
    mode?: 'drive'
    /**
     * Distance
     */
    distance: number
    /**
     * Duration
     */
    duration: number
    /**
     * Polyline
     */
    polyline: string
}

/**
 * ErrorCode
 */
export type ErrorCode =
    | 'categories.region.invalid'
    | 'places.region.invalid'
    | 'places.category.invalid'
    | 'places.orderBy.invalid'
    | 'places.orderDir.invalid'
    | 'places.limit.format'
    | 'places.cursor.format'
    | 'place.id.format'
    | 'place.id.notFound'
    | 'routes.date.range'
    | 'routes.date.format'
    | 'routes.method.invalid'
    | 'routes.places.format'
    | 'routes.places.regions'
    | 'routes.places.notFound'
    | 'routes.compute.failed'
    | 'server.internal.general'
    | 'unknown'

export type ErrorDetails = {
    [key: string]: string
}

/**
 * ErrorModel
 */
export type ErrorModel = {
    /**
     * Status
     */
    status: number
    code?: ErrorCode
    /**
     * Message
     */
    message: string
    details?: ErrorDetails | null
}

/**
 * Hours
 */
export type Hours = {
    /**
     * Timezone
     */
    timezone: string
    /**
     * Regular
     */
    regular: Array<RegularHours>
    /**
     * Exceptions
     */
    exceptions?: {
        [key: string]: unknown
    } | null
}

/**
 * Location
 */
export type Location = {
    /**
     * Address
     */
    address: string
    /**
     * Latitude
     */
    latitude: number
    /**
     * Longitude
     */
    longitude: number
}

export type PlaceId = string

/**
 * PlacePublic
 */
export type PlacePublic = {
    /**
     * Name
     */
    name: string
    description: Description
    region: Region
    category: Category
    hours?: Hours | null
    location: Location
    /**
     * Images
     */
    images?: Array<string>
    /**
     * Rating
     */
    rating?: number | null
    /**
     * Ranking
     */
    ranking?: number | null
    /**
     * Phone
     */
    phone?: string | null
    /**
     * Website
     */
    website?: string | null
    id: PlaceId
}

/**
 * PlacesPublic
 */
export type PlacesPublic = {
    /**
     * Places
     */
    places: Array<PlacePublic>
    nextCursor?: PlaceId | null
}

/**
 * Region
 */
export type Region = 'hong-kong' | 'macau'

/**
 * RegularHours
 */
export type RegularHours = {
    /**
     * Day
     */
    day: number
    /**
     * Open
     */
    open: string
    /**
     * Close
     */
    close: string
}

export type Route = WalkRoute | DriveRoute | TransitRoute

/**
 * RoutesRequest
 */
export type RoutesRequest = {
    /**
     * Date
     */
    date: string
    mode?: TravelMode | null
    /**
     * Places
     */
    places: Array<PlaceId>
}

/**
 * RoutesResponse
 */
export type RoutesResponse = {
    /**
     * Routes
     */
    routes: Array<Route>
}

/**
 * SortOrder
 */
export type SortOrder = 'asc' | 'desc'

/**
 * TransitRoute
 */
export type TransitRoute = {
    origin: PlaceId
    destination: PlaceId
    /**
     * Mode
     */
    mode?: 'transit'
    /**
     * Distance
     */
    distance: number
    /**
     * Duration
     */
    duration: number
    /**
     * Polyline
     */
    polyline: string
}

/**
 * TravelMode
 */
export type TravelMode = 'walk' | 'drive' | 'transit'

/**
 * WalkRoute
 */
export type WalkRoute = {
    origin: PlaceId
    destination: PlaceId
    /**
     * Mode
     */
    mode?: 'walk'
    /**
     * Distance
     */
    distance: number
    /**
     * Duration
     */
    duration: number
    /**
     * Polyline
     */
    polyline: string
}

export type GetCategoriesData = {
    body?: never
    path?: never
    query?: {
        /**
         * Region
         *
         * Region
         */
        region?: Region | null
    }
    url: '/categories'
}

export type GetCategoriesErrors = {
    /**
     * Unprocessable Entity
     */
    422: ErrorModel
    /**
     * Internal Server Error
     */
    500: ErrorModel
}

export type GetCategoriesError = GetCategoriesErrors[keyof GetCategoriesErrors]

export type GetCategoriesResponses = {
    /**
     * Successful Response
     */
    200: CategoriesPublic
}

export type GetCategoriesResponse = GetCategoriesResponses[keyof GetCategoriesResponses]

export type GetPlacesData = {
    body?: never
    path?: never
    query?: {
        /**
         * Region
         */
        region?: Region | null
        /**
         * Categories
         *
         * Comma-separated list
         */
        categories?: string | null
        /**
         * Orderby
         */
        orderBy?: 'id' | 'ranking' | 'rating'
        orderDir?: SortOrder
        /**
         * Limit
         */
        limit?: number
        /**
         * Cursor
         *
         * Starting id
         */
        cursor?: PlaceId | null
    }
    url: '/places'
}

export type GetPlacesErrors = {
    /**
     * Unprocessable Entity
     */
    422: ErrorModel
    /**
     * Internal Server Error
     */
    500: ErrorModel
}

export type GetPlacesError = GetPlacesErrors[keyof GetPlacesErrors]

export type GetPlacesResponses = {
    /**
     * Successful Response
     */
    200: PlacesPublic
}

export type GetPlacesResponse = GetPlacesResponses[keyof GetPlacesResponses]

export type GetPlaceByIdData = {
    body?: never
    path: {
        id: PlaceId
    }
    query?: never
    url: '/places/{id}'
}

export type GetPlaceByIdErrors = {
    /**
     * Not Found
     */
    404: ErrorModel
    /**
     * Unprocessable Entity
     */
    422: ErrorModel
    /**
     * Internal Server Error
     */
    500: ErrorModel
}

export type GetPlaceByIdError = GetPlaceByIdErrors[keyof GetPlaceByIdErrors]

export type GetPlaceByIdResponses = {
    /**
     * Successful Response
     */
    200: PlacePublic
}

export type GetPlaceByIdResponse = GetPlaceByIdResponses[keyof GetPlaceByIdResponses]

export type ComputeRoutesData = {
    body: RoutesRequest
    path?: never
    query?: never
    url: '/routes/compute'
}

export type ComputeRoutesErrors = {
    /**
     * Not Found
     */
    404: ErrorModel
    /**
     * Unprocessable Entity
     */
    422: ErrorModel
    /**
     * Internal Server Error
     */
    500: ErrorModel
}

export type ComputeRoutesError = ComputeRoutesErrors[keyof ComputeRoutesErrors]

export type ComputeRoutesResponses = {
    /**
     * Successful Response
     */
    200: RoutesResponse
}

export type ComputeRoutesResponse = ComputeRoutesResponses[keyof ComputeRoutesResponses]
