// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5019' | (string & {})
}

export type Connection = {
    type?: string | null
    locationId?: number
}

export type DayRouteRequest = {
    date?: string | null
    mode?: string | null
    placeIds?: Array<number> | null
}

export type DayRouteResponse = {
    date?: string | null
    mode?: string | null
    legs?: Array<RouteLegDto> | null
    totalDistance?: number
    totalDuration?: number
}

export type Description = {
    content?: string | null
    source?: string | null
}

export type HourException = {
    date?: string | null
    closed?: boolean | null
    open?: string | null
    close?: string | null
    notes?: string | null
}

export type Hours = {
    timezone?: string | null
    regular?: Array<RegularHour> | null
    exceptions?: Array<HourException> | null
}

export type Location = {
    address?: string | null
    latitude?: number
    longitude?: number
}

export type Place = {
    id?: number
    name?: string | null
    description?: Description
    region?: string | null
    category?: string | null
    hours?: Hours
    location?: Location
    images?: Array<string> | null
    rating?: number | null
    ranking?: number | null
    phone?: string | null
    website?: string | null
    _connection?: Connection
}

export type RegularHour = {
    day?: number
    open?: string | null
    close?: string | null
}

export type RouteLegDto = {
    fromPlaceId?: number
    toPlaceId?: number
    distance?: number
    duration?: number
    travelMode?: string | null
    steps?: Array<RouteStepDto> | null
}

export type RouteStepDto = {
    stepTravelMode?: string | null
    distance?: number | null
    duration?: number | null
    instruction?: string | null
    transit?: TransitStepDto
}

export type TransitStepDto = {
    lineName?: string | null
    vehicleType?: string | null
    departureStopName?: string | null
    arrivalStopName?: string | null
    stopCount?: number | null
}

export type GetCategoriesData = {
    body?: never
    path?: never
    query?: {
        region?: string
    }
    url: '/categories'
}

export type GetCategoriesResponses = {
    /**
     * Success
     */
    200: Array<string>
}

export type GetCategoriesResponse =
    GetCategoriesResponses[keyof GetCategoriesResponses]

export type GetPlacesData = {
    body?: never
    path?: never
    query?: {
        region?: string
        categories?: string
        orderBy?: string
        orderDir?: string
        limit?: number
    }
    url: '/places'
}

export type GetPlacesResponses = {
    /**
     * Success
     */
    200: Array<Place>
}

export type GetPlacesResponse = GetPlacesResponses[keyof GetPlacesResponses]

export type GetPlacesByIdData = {
    body?: never
    path: {
        id: number
    }
    query?: never
    url: '/places/{id}'
}

export type GetPlacesByIdResponses = {
    /**
     * Success
     */
    200: Place
}

export type GetPlacesByIdResponse =
    GetPlacesByIdResponses[keyof GetPlacesByIdResponses]

export type PostRoutesDayData = {
    body?: DayRouteRequest
    path?: never
    query?: never
    url: '/routes/day'
}

export type PostRoutesDayResponses = {
    /**
     * Success
     */
    200: DayRouteResponse
}

export type PostRoutesDayResponse =
    PostRoutesDayResponses[keyof PostRoutesDayResponses]
